version: '3.8'
services:
  price-craft-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_BUILD_TARGET:-production}
    container_name: craft-price-back
    ports:
      - '${DOCKER_PROD_PORT:-4000}:${PORT:-4000}'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - localnet

networks:
  localnet:
    external: true
    name: localnet
